services:
  mysql:
    container_name: mysql
    image: mysql:latest
    #entrypoint: ["mysqld"]
    #command: ["--skip-grant-tables"]
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - setup:/docker-entrypoint-initdb.d      
    environment:
      MYSQL_ROOT_PASSWORD: myroot
      MYSQL_USER: demo
      MYSQL_PASSWORD: myroot
      MYSQL_DATABASE: demo
    healthcheck:
      test: mysqladmin ping -h localhost
      timeout: 20s
      retries: 10      
      start_period: 30s
      start_interval: 2s
    depends_on:
      init-container:
        condition:
          service_completed_successfully      
  init-container:
    container_name: init-postgresql
    image: mysql:latest
    volumes:
      - setup:/docker-entrypoint-initdb.d
    command:
        - bash
        - -c 
        - |
          cat <<EOF > /docker-entrypoint-initdb.d/init-demo-db.sql
            FLUSH PRIVILEGES;
            GRANT ALL PRIVILEGES ON demo.* TO 'root '@'%';
          EOF
          cat <<HEREFILE > /etc/mysql/conf.d/demo-plugin.cnf
            [mysqld]
              ;default-authentication-plugin=mysql_native_password
          HEREFILE
volumes:
  setup:
  mysql-data: